### PR TITLE
Add Docker build action

### PR DESCRIPTION
**Pull request by kruton**
This will allow the pg_back application to be built into Docker container that is published on GitHub Repository and used by Docker or Kubernetes instances. It contributes a bit to #75.

### CODE REVIEW

**Comment by kruton** [comment]
You can look at the ouputs in the packages section of https://github.com/kruton/pg_back

**Comment by orgrim** [comment]
Hi, in your docker image, pg_back can't get pg_dump from the PATH:

```
$ docker run -it --rm ghcr.io/kruton/pg_back:latest 
2023/08/22 19:52:18 WARN: failed to retrieve version of pg_dump: exec: "pg_dump": executable file not found in $PATH
2023/08/22 19:52:18 FATAL: provided pg_dump is older than 8.4, unable use it.
```

Maybe the PostgreSQL binaries aren't installed in the standard directories in Alpine? (Sorry I don't know this distribution)

**Comment by kruton** [comment]
Did you use the latest one? The first try I just had a bare Golang binary in the container before I realized pg_dumpall is needed. Now with Alpine it should work:

```
$ docker pull ghcr.io/kruton/pg_back:latest
latest: Pulling from kruton/pg_back
Digest: sha256:c4ed1c8b0e8a7f0888b0adf62872189193f543e3489806468eebe80467760f06
Status: Image is up to date for ghcr.io/kruton/pg_back:latest
ghcr.io/kruton/pg_back:latest
$ docker run -it --rm ghcr.io/kruton/pg_back:latest
2023/08/23 22:49:36 INFO: dumping globals
2023/08/23 22:49:36 INFO: waiting for postprocessing to complete
2023/08/23 22:49:36 FATAL: pg_dumpall -g failed: mkdir /var/backups: permission denied
```

**Comment by kruton** [comment]
I just updated the Dockerfile to accept PUID and PGID environment variables to set which UID and GID to run the docker container as.

To test this:

```shell
docker pull ghcr.io/kruton/pg_back:latest
docker run --rm --name test-pg -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres
mkdir backups
until docker logs test-pg | grep 'ready to accept'; do sleep 1; done
docker run --rm -v ./backups:/var/backups -e PUID=$(id -u) -e PGPASSWORD=password --net=host ghcr.io/kruton/pg_back:latest -h 127.0.0.1 -p 5432 -U postgres
docker kill test-pg
```

**Comment by orgrim** [comment]
Hi, the later image can access the client tools from postgres.

On the user/group env vars, this do not work with -u option of docker, and seems redundant with it, so I may lack context on why it's needed.

Apart from that, it looks good and CI works.

Regards,

**Comment by kruton** [comment]
Yes, maybe you can just use `securityContext.runAsUser` for the same purpose in Kubernetes. Of course with Docker you can use `-u` argument.

I can revert that change since it makes the image a few megabytes bigger for the required packages ("shadow"). I'll add documentation for how to use the docker build as well along with a `docker-compose.yml` and a Kubernetes deployment example.

**Comment by kruton** [comment]
I added an example configuration for `docker-compose.yml` and a working example for Kubernetes CronJob. The `docker-compose` file is also used to test `pg_back` against several major versions of Postgres.

**Comment by orgrim** [comment]
Thanks a lot for this contribution!

**Pull request merged**
