### PR TITLE
try to save files with a more sane file permission values

### PR DESCRIPTION
**Pull request by mlusetti**
simply let the owner (the user who run the command) be able to read the files

while here ... remove io/ioutil where necessary

### CODE REVIEW

**Comment by orgrim** [comment]
Hi, all those function that set FileModes run before applying umask, this patch forces no permissions on group an others that could be archived by setting the umask to 0077. Also the file aren't writable be anyone other than the user, so "sane" seems subject to interpretation here IMO.

**Comment by mlusetti** [comment]
I mean db dumps can contain sensitive information so they should not be readable by anyone in first place.

For the umask thing, I could get where you're headed but I'm not sure I understand fully what you're saying.

**Comment by orgrim** [comment]
Hi, would you mind rebasing your branch, so that I can merge the PR, please?

**Comment by orgrim** [comment]
Merged by hand, thanks!

**Comment by mlusetti** [comment]
Thank you.

**Comment by yhuelf** [comment]
Hi, I think it would be better if pg_back would log a warning message instead of returning an error message when the chmod operation fails.

**Pull request closed without merging**
